version: "3"
tasks:
    install:
        cmds:
            - go install

    docs:
        cmds:
            - go generate ./...

    plan:
        cmds:
            - { task: "install" }
            - terraform -chdir=demo plan

    apply:
        cmds:
            - { task: "install" }
            - terraform -chdir=demo apply -auto-approve

    destroy:
        cmds:
            - { task: "install" }
            - terraform -chdir=demo destroy
