package shift_left_bitbucket_account_test

import (
	"testing"

	"terraform-provider-orcasecurity/orcasecurity"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// Read reports installation_mode verbatim, so a unit still on the legacy SCAN_ALL
// keeps that value instead of being displayed as SELECTED_REPOSITORIES. Import is the
// only path that puts it in state — create and update both write first, and the write
// remaps SCAN_ALL before it can persist — so this is the case that exercises it.
//
// installation_mode is Optional+Computed, so a config that omits it carries the state
// value into the plan. Carrying SCAN_ALL forward unchanged would plan a value the write
// path never sends, and the apply would fail with "inconsistent result after apply".
func TestScmUnitApply_ImportedLegacyScanAllMigratesOnApply(t *testing.T) {
	stub := newSCMUnitStub()
	stub.unit["installation_mode"] = "SCAN_ALL"
	stub.start(t)

	config := stubConfig(`  configuration_settings = { pr_summary_appendix = "a" }`)
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: orcasecurity.TestAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				// Import writes nothing, so Read's SCAN_ALL is what lands in state.
				Config:             config,
				ResourceName:       stubResourceName,
				ImportState:        true,
				ImportStatePersist: true,
				ImportStateId:      stubInstallationID + "/" + stubAccountSlug,
				Check: resource.TestCheckResourceAttr(stubResourceName,
					"installation_mode", "SCAN_ALL"),
			},
			{
				// The apply migrates it to what the API actually stores.
				Config: config,
				Check: resource.TestCheckResourceAttr(stubResourceName,
					"installation_mode", "SELECTED_REPOSITORIES"),
			},
		},
	})
}

// The migration write is generated by the installation_mode plan modifier, so the
// configuration alone looks like a no-op: config-vs-state comparison cannot see it,
// and the framework never marks Computed attributes unknown for it (the proposed
// plan still equals prior state when that decision is made). If the migration write
// then moves a server-owned value, a carried-forward volatile attribute fails the
// apply with "inconsistent result after apply". The volatile modifiers must plan
// unknown whenever state still holds a legacy SCAN_ALL.
func TestScmUnitApply_ImportedLegacyScanAllWithVolatileSideEffects(t *testing.T) {
	stub := newSCMUnitStub()
	stub.volatileSideEffects = true
	stub.unit["installation_mode"] = "SCAN_ALL"
	stub.unit["integrated_repositories_count"] = 12
	stub.unit["scan_all_state"] = "RUNNING"
	stub.start(t)

	config := stubConfig(``)
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: orcasecurity.TestAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config:             config,
				ResourceName:       stubResourceName,
				ImportState:        true,
				ImportStatePersist: true,
				ImportStateId:      stubInstallationID + "/" + stubAccountSlug,
				Check: resource.TestCheckResourceAttr(stubResourceName,
					"scan_all_state", "RUNNING"),
			},
			{
				// The migration write halts enrollment server-side; state must pick
				// up the moved volatile values instead of failing the apply.
				Config: config,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr(stubResourceName, "installation_mode", "SELECTED_REPOSITORIES"),
					resource.TestCheckResourceAttr(stubResourceName, "scan_all_state", "STOPPED"),
					resource.TestCheckResourceAttr(stubResourceName, "integrated_repositories_count", "5"),
				),
			},
		},
	})
}
